import Foundation

enum GameDifficulty: String, CaseIterable, Identifiable {
    case easy = "Easy"
    case medium = "Medium"
    case hard = "Hard"

    var id: String { self.rawValue }

    var associatedClubs: Set<String> {
        switch self {
        case .easy:
            return [
                "AC Milan",
                "Ajax Amsterdam",
                "Arsenal FC",
                "Atlético de Madrid",
                "Bayern Munich",
                "Borussia Dortmund",
                "CA Boca Juniors",
                "CA River Plate",
                "CR Flamengo",
                "Chelsea FC",
                "FC Barcelona",
                "Inter Miami CF",
                "Inter Milan",
                "Juventus FC",
                "Liverpool FC",
                "Manchester City",
                "Manchester United",
                "Paris Saint-Germain",
                "Real Madrid",
                "SSC Napoli",
                "Tottenham Hotspur",
            ]
        case .medium:
            return [
                "1.FC Köln",
                "1.FC Union Berlin",
                "1.FSV Mainz 05",
                "ACF Fiorentina",
                "AEK Athens",
                "AFC Bournemouth",
                "AS Monaco",
                "AS Roma",
                "AZ Alkmaar",
                "Al-Ahli SFC",
                "Al-Ettifaq FC",
                "Al-Hilal SFC",
                "Al-Ittihad Club",
                "Al-Nassr FC",
                "Al-Shabab FC",
                "Aris Thessaloniki",
                "Aston Villa",
                "Atalanta BC",
                "Athletic Bilbao",
                "Atlanta United",
                "BSC Young Boys",
                "Basaksehir FK",
                "Bayer 04 Leverkusen",
                "Benfica",
                "Besiktas JK",
                "Bologna FC 1909",
                "Borussia Mönchengladbach",
                "Botafogo de Futebol e Regatas",
                "Brentford FC",
                "Brighton & Hove Albion",
                "CF América",
                "Celta de Vigo",
                "Celtic FC",
                "Club Brugge",
                "Clube Atlético Mineiro",
                "Clube de Regatas Vasco da Gama",
                "Columbus Crew",
                "Cruzeiro Esporte Clube",
                "Crystal Palace",
                "Eintracht Frankfurt",
                "Everton FC",
                "FC Augsburg",
                "FC Basel 1893",
                "FC Copenhagen",
                "FC Toulouse",
                "FC Twente Enschede",
                "FC Utrecht",
                "FC Zürich",
                "FK Partizan Belgrade",
                "Fenerbahce",
                "Feyenoord Rotterdam",
                "Fluminense Football Club",
                "Fulham FC",
                "Galatasaray",
                "Genoa CFC",
                "Grêmio Foot-Ball Porto Alegrense",
                "Hamburger SV",
                "Ipswich Town",
                "KRC Genk",
                "LOSC Lille",
                "Leeds United",
                "Los Angeles FC",
                "Los Angeles Galaxy",
                "New York City FC",
                "Newcastle United",
                "Nottingham Forest",
                "OGC Nice",
                "Olympiacos Piraeus",
                "Olympique Lyon",
                "Olympique Marseille",
                "PAOK Thessaloniki",
                "PSV Eindhoven",
                "Panathinaikos",
                "Portland Timbers",
                "Porto",
                "RB Leipzig",
                "RC Lens",
                "RSC Anderlecht",
                "Racing Club",
                "Rangers",
                "Real Betis Balompié",
                "Real Sociedad",
                "Red Bull New York",
                "Red Star Belgrade",
                "Royal Antwerp FC",
                "SC Braga",
                "SC Freiburg",
                "SS Lazio",
                "SV Werder Bremen",
                "Santos FC",
                "Seattle Sounders FC",
                "Sevilla FC",
                "Sociedade Esportiva Palmeiras",
                "Sport Club Corinthians Paulista",
                "Sport Club Internacional",
                "Sporting CP",
                "Stade Rennais FC",
                "Sunderland AFC",
                "São Paulo Futebol Clube",
                "TSG 1899 Hoffenheim",
                "Torino FC",
                "Toronto FC",
                "Trabzonspor",
                "Udinese Calcio",
                "Union Saint-Gilloise",
                "Urawa Red Diamonds",
                "Valencia CF",
                "VfB Stuttgart",
                "Villarreal CF",
                "Vissel Kobe",
            ]
        case .hard:
            return [
                "AC Monza",
                "ADO Den Haag",
                "AJ Auxerre",
                "Angers SCO",
                "Associação Chapecoense de Futebol",
                "CA Osasuna",
                "Cagliari Calcio",
                "Club Athletico Paranaense",
                "Clube do Remo (PA)",
                "Como 1907",
                "Coritiba Foot Ball Club",
                "Coventry City",
                "Deportivo A Coruña",
                "Deportivo Alavés",
                "ESTAC Troyes",
                "Elche CF",
                "Esporte Clube Bahia",
                "Esporte Clube Vitória",
                "Excelsior Rotterdam",
                "FC Groningen",
                "FC Lorient",
                "FC Schalke 04",
                "Fortuna Sittard",
                "Frosinone Calcio",
                "Getafe CF",
                "Go Ahead Eagles",
                "Hull City",
                "Le Havre AC",
                "Le Mans FC",
                "Levante UD",
                "Mirassol Futebol Clube (SP)",
                "Málaga CF",
                "NEC Nijmegen",
                "PEC Zwolle",
                "Paris FC",
                "Parma Calcio 1913",
                "RC Strasbourg Alsace",
                "RCD Espanyol Barcelona",
                "Racing Santander",
                "Rayo Vallecano",
                "Red Bull Bragantino",
                "SC Cambuur Leeuwarden",
                "SC Heerenveen",
                "SC Paderborn 07",
                "SC Telstar",
                "SV 07 Elversberg",
                "Sparta Rotterdam",
                "Stade Brestois 29",
                "US Lecce",
                "US Sassuolo",
                "Venezia FC",
                "Vitória Guimarães",
                "Willem II Tilburg",
            ]
        }
    }
}
