import Foundation

enum CountryFlags {

    static func flag(for country: String) -> String {
        let key = country
            .folding(options: .diacriticInsensitive, locale: .current)
            .lowercased()
            .trimmingCharacters(in: .whitespacesAndNewlines)

        return map[key] ?? "🏳️"
    }

    static func primaryFlag(from nationalities: [String]) -> String {
        guard let first = nationalities.first else { return "🏳️" }
        return flag(for: first)
    }

    private static let map: [String: String] = [
        "argentina": "🇦🇷",
        "uruguay": "🇺🇾",
        "brazil": "🇧🇷",
        "spain": "🇪🇸",
        "france": "🇫🇷",
        "germany": "🇩🇪",
        "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "portugal": "🇵🇹",
        "netherlands": "🇳🇱",
        "belgium": "🇧🇪",
        "italy": "🇮🇹",
        "croatia": "🇭🇷",
        "serbia": "🇷🇸",
        "poland": "🇵🇱",
        "ukraine": "🇺🇦",
        "russia": "🇷🇺",
        "turkey": "🇹🇷",
        "turkiye": "🇹🇷",
        "morocco": "🇲🇦",
        "senegal": "🇸🇳",
        "nigeria": "🇳🇬",
        "ghana": "🇬🇭",
        "cameroon": "🇨🇲",
        "ivory coast": "🇨🇮",
        "cote d'ivoire": "🇨🇮",
        "egypt": "🇪🇬",
        "algeria": "🇩🇿",
        "tunisia": "🇹🇳",
        "south africa": "🇿🇦",
        "mexico": "🇲🇽",
        "usa": "🇺🇸",
        "united states": "🇺🇸",
        "canada": "🇨🇦",
        "colombia": "🇨🇴",
        "chile": "🇨🇱",
        "ecuador": "🇪🇨",
        "peru": "🇵🇪",
        "venezuela": "🇻🇪",
        "paraguay": "🇵🇾",
        "bolivia": "🇧🇴",
        "japan": "🇯🇵",
        "south korea": "🇰🇷",
        "korea, south": "🇰🇷",
        "china": "🇨🇳",
        "australia": "🇦🇺",
        "saudi arabia": "🇸🇦",
        "qatar": "🇶🇦",
        "iran": "🇮🇷",
        "iraq": "🇮🇶",
        "israel": "🇮🇱",
        "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
        "northern ireland": "🇬🇧",
        "ireland": "🇮🇪",
        "republic of ireland": "🇮🇪",
        "denmark": "🇩🇰",
        "sweden": "🇸🇪",
        "norway": "🇳🇴",
        "finland": "🇫🇮",
        "iceland": "🇮🇸",
        "austria": "🇦🇹",
        "switzerland": "🇨🇭",
        "czech republic": "🇨🇿",
        "czechia": "🇨🇿",
        "slovakia": "🇸🇰",
        "hungary": "🇭🇺",
        "romania": "🇷🇴",
        "bulgaria": "🇧🇬",
        "greece": "🇬🇷",
        "slovenia": "🇸🇮",
        "bosnia-herzegovina": "🇧🇦",
        "montenegro": "🇲🇪",
        "north macedonia": "🇲🇰",
        "albania": "🇦🇱",
        "georgia": "🇬🇪",
        "armenia": "🇦🇲",
        "azerbaijan": "🇦🇿",
        "kazakhstan": "🇰🇿",
        "uzbekistan": "🇺🇿",
        "costa rica": "🇨🇷",
        "panama": "🇵🇦",
        "jamaica": "🇯🇲",
        "honduras": "🇭🇳",
        "guatemala": "🇬🇹",
        "el salvador": "🇸🇻",
        "curacao": "🇨🇼",
        "suriname": "🇸🇷",
        "philippines": "🇵🇭",
        "indonesia": "🇮🇩",
        "thailand": "🇹🇭",
        "vietnam": "🇻🇳",
        "india": "🇮🇳",
        "new zealand": "🇳🇿",
        "zimbabwe": "🇿🇼",
        "zambia": "🇿🇲",
        "mali": "🇲🇱",
        "guinea": "🇬🇳",
        "gabon": "🇬🇦",
        "angola": "🇦🇴",
        "democratic republic of the congo": "🇨🇩",
        "congo dr": "🇨🇩",
        "dr congo": "🇨🇩",
        "congo": "🇨🇬",
        "togo": "🇹🇬",
        "benin": "🇧🇯",
        "burkina faso": "🇧🇫",
        "cape verde": "🇨🇻",
        "cabo verde": "🇨🇻",
        "liberia": "🇱🇷",
        "sierra leone": "🇸🇱",
        "kenya": "🇰🇪",
        "uganda": "🇺🇬",
        "tanzania": "🇹🇿",
        "namibia": "🇳🇦",
        "mozambique": "🇲🇿",
        "madagascar": "🇲🇬",
        "haiti": "🇭🇹",
        "dominican republic": "🇩🇴",
        "trinidad and tobago": "🇹🇹",
        "cyprus": "🇨🇾",
        "luxembourg": "🇱🇺",
        "estonia": "🇪🇪",
        "latvia": "🇱🇻",
        "lithuania": "🇱🇹",
        "belarus": "🇧🇾",
        "moldova": "🇲🇩",
        "kosovo": "🇽🇰",
        "malta": "🇲🇹",
        "andorra": "🇦🇩",
        "san marino": "🇸🇲",
        "liechtenstein": "🇱🇮",
        "faroe islands": "🇫🇴",
        "gibraltar": "🇬🇮",
    ]
}
