#!/usr/bin/env python3
"""
Publish ClubDatabase.json for over-the-air updates via Firebase Hosting.

Flow:
  1. Load ClubDatabase.json
  2. Apply test/Database/player_overrides.json (transfers / field edits)
  3. Write web/data/{ClubDatabase.json, manifest.json}
  4. Optionally firebase deploy --only hosting

Usage:
  python3 scripts/publish_remote_data.py              # prepare web/data/ only
  python3 scripts/publish_remote_data.py --upload     # prepare + deploy hosting
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from player_overrides_lib import (  # noqa: E402
    DATABASE_PATH,
    apply_all_overrides,
    load_database,
    load_overrides,
)

OUT_DIR = ROOT / "web" / "data"
VERSION_PATH = OUT_DIR / "VERSION"

# Public CDN base (Firebase Hosting for project ftmp-8a367).
HOSTING_BASE = "https://ftmp-8a367.web.app/data"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def next_version() -> int:
    if VERSION_PATH.exists():
        try:
            return int(VERSION_PATH.read_text().strip()) + 1
        except ValueError:
            pass
    return 1


def prepare() -> None:
    if not DATABASE_PATH.exists():
        sys.exit(f"Missing database: {DATABASE_PATH}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    version = next_version()

    data = load_database()
    overrides = load_overrides()
    if overrides:
        print(f"Applying {len(overrides)} player override(s)…")
        for line in apply_all_overrides(data, overrides):
            print(f"  • {line}")
    else:
        print("No player overrides.")

    db_bytes = (json.dumps(data, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    checksum = sha256_bytes(db_bytes)

    db_out = OUT_DIR / "ClubDatabase.json"
    db_out.write_bytes(db_bytes)

    manifest = {
        "version": version,
        "updatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z"),
        "database": {
            "url": f"{HOSTING_BASE}/ClubDatabase.json",
            "sha256": checksum,
        },
    }

    manifest_out = OUT_DIR / "manifest.json"
    manifest_out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    VERSION_PATH.write_text(str(version) + "\n", encoding="utf-8")

    (OUT_DIR / ".gitignore").write_text(
        "# Generated by scripts/publish_remote_data.py — do not commit the DB dump.\n"
        "ClubDatabase.json\n"
        "VERSION\n",
        encoding="utf-8",
    )

    print(f"Prepared version {version}")
    print(f"  {manifest_out}")
    print(f"  {db_out}  ({len(db_bytes) / 1_000_000:.1f} MB)")
    print(f"  sha256: {checksum}")
    print(f"  manifest URL: {HOSTING_BASE}/manifest.json")


def upload() -> None:
    print("Deploying web/ (including data/) to Firebase Hosting…")
    try:
        subprocess.run(
            ["npx", "--yes", "firebase-tools", "deploy", "--only", "hosting"],
            cwd=ROOT,
            check=True,
        )
    except FileNotFoundError:
        sys.exit("npx not found — install Node.js first.")
    except subprocess.CalledProcessError as exc:
        sys.exit(
            f"Deploy failed ({exc.returncode}).\n"
            "Run once:  npx firebase-tools login\n"
            "Then retry: python3 scripts/publish_remote_data.py --upload"
        )
    print(f"\nLive at: {HOSTING_BASE}/manifest.json")
    print("Existing installs pick this up on the next launch(es).")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--upload",
        action="store_true",
        help="Deploy web/data to Firebase Hosting (requires firebase login)",
    )
    args = parser.parse_args()

    prepare()
    if args.upload:
        upload()
    else:
        print(
            "\nNext — one-time login, then publish:\n"
            "  npx firebase-tools login\n"
            "  python3 scripts/publish_remote_data.py --upload\n"
        )


if __name__ == "__main__":
    main()
